modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="copyl"
version="3.3.0"
displayName="OreSpawn Reforged"
authors="Santi-PdR"
displayURL="https://github.com/Santi-PdR/OreSpawn"
description='''
OreSpawn Reforged para Forge 1.20.1: port progresivo del contenido del OreSpawn 1.12.2 proporcionado,
conservando sus criaturas, objetos, estructuras, comportamiento y assets originales lo más fielmente posible.
'''
displayTest="MATCH_VERSION"

[[dependencies.copyl]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.copyl]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
